### ISSUE TITLE
Release v0.2.2

### ISSUE THREAD

**Issue by AlexFrax** [coltoneshaw/3c-portfolio-manager#13]
Hello,

thanks for the update. Here are my few observations.

Bot planner tab - The manager is showing me only 34 active bots, despite I have 53 of them. I´m using single bots only.
![image](https://user-images.githubusercontent.com/72823262/130494479-869ba47c-5657-4d1e-8a50-73d92eb497d9.png)
![image](https://user-images.githubusercontent.com/72823262/130494593-68e6e49b-e44c-4658-b966-21444cae917c.png)

Stats tab - Dates in Profit by day are missing.
![image](https://user-images.githubusercontent.com/72823262/130494772-8201363a-3890-4e8f-8f34-cf7fd846ee0d.png)

Average daily profit in Performance monitor showing me wrong number. There should be 60 instead of 45 same as it´s visible on the picture above.
![image](https://user-images.githubusercontent.com/72823262/130495155-c377cab5-60e5-4140-af03-e1ce2ff75f94.png)

I´m using Win x64 version.

Best regards
Alex

**Comment by coltoneshaw** [comment]
@AlexFrax - I think I have a fix for two of the three issues.

1. Bot's data is missing some bots - We confirmed this fix on Discord
2. The avg in performance metrics was incorrect. I believe I added an additional day into the calcs which is fixed. If you can test with the attached build
3. Invalid date - I'm not entirely sure what is throwing this error. I added additional handling into the date function to resolve this and a console log for the array to see what the data looks like. Can you test with the attached build and confirm the fixes? If this one is not fixed run the below in your javascript console and attach a screenshot of the result.

```javascript
function getLang() {
  if (navigator.languages != undefined) 
    return navigator.languages[0]; 
  return navigator.language;
}
getLang() 
```

Additionally, can you attach a screenshot of the date array from the console. It should look like the below photo. Thanks!
<img width="326" alt="Screen Shot 2021-08-23 at 11 46 38 PM" src="https://user-images.githubusercontent.com/46071821/130552622-e79c0622-b982-45d6-a860-50515e4ad472.png">

**Comment by AlexFrax** [comment]
I downloaded the beta build from the link above, but point 2 and 3 are still not fixed. I tried to toggle developer tool, but after I clicked on it, nothing happened. Also tried to pres CTRL+SHIFT+I but nothing happened as weel. Can you please help me how to open the console?

I´m attaching the picture that I really have opened version 0.2.3. below.
![image](https://user-images.githubusercontent.com/72823262/130763136-3651f6a6-50b3-441a-84c3-3cd6ae41edd5.png)

**Comment by AlexFrax** [comment]
I´m adding creen from javascript console from browser. Hopefully it will be helpfull. 
![image](https://user-images.githubusercontent.com/72823262/130766141-05e70589-fe12-4e30-8bd0-10a0d33987aa.png)

Unfortunately I don´t know how to get to data similar from the second screenshot with date array.

**Comment by coltoneshaw** [comment]
<img width="562" alt="Screen Shot 2021-08-29 at 2 48 10 PM" src="https://user-images.githubusercontent.com/46071821/131261971-156b152c-9245-412e-90c6-33872ecdd702.png">
<img width="576" alt="Screen Shot 2021-08-29 at 2 48 17 PM" src="https://user-images.githubusercontent.com/46071821/131261973-934ce728-0e8a-4051-a32e-ff1819d5b748.png">

No worries! The `cs-CZ` was enough for me to locate the issue. I believe I've fixed the problem and should have a fix coming out in a patch release soon. Can you confirm these dates are formatted correctly for you?

**Comment by AlexFrax** [comment]
Yes, the date format is OK. Perfect! Thanks a lot! :)
